<script type="text/javascript">

    Ext.require([
        'Ext.grid.*',
        'Ext.data.*',
        'Ext.panel.*',
        'Ext.layout.container.Border'
    ]);

    Ext.onReady(function () {
        Ext.define('Statistic', {
            extend: 'Ext.data.Model',
            fields: [
                'ip',
                'browser',
                'operating_system',
                'url_came',
                'url_went',
                'count_uniqe_url',
            ]
        });

        var store = Ext.create('Ext.data.Store', {
            model: 'Statistic',
            pageSize: 10,
            proxy: {
                type: 'ajax',
                url: '<?= $this->basePath('/api/v1/index') ?>',
                reader: {
                    type: 'json',
                    rootProperty: 'response'
                }
            },
            autoLoad: true
        });

        console.log(store.getData().items);

        var grid = Ext.create('Ext.grid.Panel', {
            bufferedRenderer: false,
            pageSize: 10,
            store: store,
            plugins: 'gridfilters',
            closable: true,
            autoScroll: true,
            columns: [
                {
                    text: "IP", width: 70, dataIndex: 'ip', sortable: false,
                    filter: {
                        type: 'string'
                    }
                },
                {text: "Броузер", width: 70, dataIndex: 'browser', sortable: true},
                {text: "ОС", width: 70, dataIndex: 'operating_system', sortable: true},
                {text: "URL с которого зашел", width: 125, dataIndex: 'url_came', sortable: false},
                {text: "URL на который зашел", width: 125, dataIndex: 'url_went', sortable: false},
                {text: "Число уникальных просмотренных URL", width: 60, dataIndex: 'count_uniqe_url', sortable: false}
            ],
            forceFit: true,
            bbar: Ext.create('Ext.PagingToolbar', {
                pageSize: 3,
                store: store,
                dock: 'bottom',
                displayInfo: true
            }),
            split: true,
            region: 'north'
        });

        Ext.create('Ext.Panel', {
            renderTo: Ext.getBody(),
            frame: false,
            title: '',
            height: 400,
            layout: 'border',
            items: [
                grid
            ]
        });


        store.load();
    });

</script>





